-- Priority source expansion for higher-trust Malawi job coverage.
-- LinkedIn is registered for visibility but disabled until an approved API/feed
-- or partner workflow is used.

INSERT INTO public.job_ingestion_sources (
    name,
    slug,
    connector_type,
    base_url,
    feed_url,
    default_location,
    is_enabled,
    auto_publish,
    crawl_frequency_minutes,
    reputation_score,
    terms_reviewed,
    attribution_required,
    compliance_notes,
    selector_config,
    path_whitelist,
    path_blacklist,
    discovery_keywords
)
VALUES
    (
        'LinkedIn Malawi Jobs',
        'linkedin-malawi-jobs',
        'CAREER_PAGE',
        'https://www.linkedin.com/jobs/jobs-in-malawi',
        NULL,
        'Malawi',
        false,
        false,
        720,
        95,
        false,
        true,
        'High-priority discovery source, but direct scraping is disabled. Use an approved LinkedIn API/partner/manual import workflow before enabling.',
        '{"maxLinks": 40, "linkIncludeKeywords": ["jobs/view", "malawi"], "linkExcludeKeywords": ["login", "signup", "checkpoint"]}'::jsonb,
        ARRAY['/jobs/'],
        ARRAY['/company/', '/learning/', '/pulse/', '/login', '/signup'],
        ARRAY['malawi', 'bank', 'telecom', 'government', 'parastatal']
    ),
    (
        'First Capital / FMBCH Careers',
        'first-capital-fmbch-careers',
        'CAREER_PAGE',
        'https://fmbcapitalgroup.com/careers/',
        NULL,
        'Malawi',
        true,
        false,
        720,
        90,
        true,
        true,
        'Official First Capital/FMBCH careers page. Group page may include non-Malawi roles, so admin review remains required.',
        '{"maxLinks": 25, "linkIncludeKeywords": ["vacancy", "vacancies", "career", "developer", "officer", "manager", "analyst", "apply"]}'::jsonb,
        ARRAY['/careers', '/career', '/vacanc'],
        ARRAY['privacy', 'terms', 'facebook', 'instagram', 'linkedin'],
        ARRAY['vacancy', 'career', 'apply', 'malawi', 'blantyre', 'lilongwe']
    ),
    (
        'NBS Bank Careers',
        'nbs-bank-careers',
        'CAREER_PAGE',
        'https://nbs.mw/careers-at-nbs/',
        NULL,
        'Malawi',
        true,
        false,
        720,
        88,
        true,
        true,
        'Official NBS Bank careers page.',
        '{"maxLinks": 20, "linkIncludeKeywords": ["career", "careers", "vacancy", "vacancies", "apply", "job"]}'::jsonb,
        ARRAY['career', 'vacanc', 'job'],
        ARRAY['privacy', 'terms', 'facebook', 'instagram', 'linkedin'],
        ARRAY['career', 'vacancy', 'apply', 'bank']
    ),
    (
        'National Bank of Malawi Careers',
        'national-bank-malawi-careers',
        'CAREER_PAGE',
        'https://www.natbank.co.mw/22-national-bank/about-us/43-careers-at-national-bank-of-malawi',
        NULL,
        'Malawi',
        false,
        false,
        720,
        88,
        true,
        true,
        'Official page registered but disabled because the current page appears broad/static; enable after selector review.',
        '{"maxLinks": 20, "linkIncludeKeywords": ["career", "vacancy", "job", "apply"]}'::jsonb,
        ARRAY['career', 'vacanc', 'job'],
        ARRAY['privacy', 'terms', 'facebook', 'instagram', 'linkedin'],
        ARRAY['career', 'vacancy', 'bank']
    ),
    (
        'FDH Bank Careers',
        'fdh-bank-careers',
        'CAREER_PAGE',
        'https://www.fdh.co.mw/',
        NULL,
        'Malawi',
        false,
        false,
        720,
        86,
        false,
        true,
        'Official FDH website registered but disabled until the exact careers/vacancies page is confirmed.',
        '{"maxLinks": 20, "linkIncludeKeywords": ["career", "careers", "vacancy", "vacancies", "apply"]}'::jsonb,
        ARRAY['career', 'vacanc', 'job'],
        ARRAY['privacy', 'terms', 'facebook', 'instagram', 'linkedin'],
        ARRAY['career', 'vacancy', 'bank']
    ),
    (
        'Standard Bank Group Careers',
        'standard-bank-group-careers',
        'CAREER_PAGE',
        'https://www.standardbank.com/sbg/standard-bank-group/careers',
        NULL,
        'Malawi',
        false,
        false,
        720,
        88,
        true,
        true,
        'Official Standard Bank careers page registered but disabled until Malawi-specific filtering/API path is confirmed.',
        '{"maxLinks": 30, "linkIncludeKeywords": ["career", "jobs", "vacancy", "apply", "malawi"]}'::jsonb,
        ARRAY['career', 'job', 'vacanc'],
        ARRAY['privacy', 'terms', 'facebook', 'instagram', 'linkedin'],
        ARRAY['malawi', 'career', 'bank']
    ),
    (
        'Airtel Malawi Careers',
        'airtel-malawi-careers',
        'CAREER_PAGE',
        'https://www.airtel.mw/career',
        NULL,
        'Malawi',
        true,
        false,
        720,
        90,
        true,
        true,
        'Official Airtel Malawi careers page.',
        '{"maxLinks": 25, "linkIncludeKeywords": ["career", "vacancy", "vacancies", "job", "apply", "opportunities"]}'::jsonb,
        ARRAY['career', 'vacanc', 'job', 'opportunit'],
        ARRAY['privacy', 'terms', 'facebook', 'instagram', 'linkedin'],
        ARRAY['career', 'vacancy', 'airtel', 'apply']
    ),
    (
        'TNM Vacancies',
        'tnm-vacancies',
        'CAREER_PAGE',
        'https://www.tnm.co.mw/vacancies/',
        NULL,
        'Malawi',
        true,
        false,
        360,
        90,
        true,
        true,
        'Official Telekom Networks Malawi vacancies section.',
        '{"maxLinks": 30, "linkIncludeKeywords": ["vacancies", "vacancy", "job", "manager", "officer", "assistant", "analyst", "specialist"]}'::jsonb,
        ARRAY['/vacancies/'],
        ARRAY['privacy', 'terms', 'facebook', 'instagram', 'linkedin'],
        ARRAY['vacancy', 'vacancies', 'tnm', 'apply']
    ),
    (
        'Malawi Revenue Authority Careers',
        'mra-careers',
        'CAREER_PAGE',
        'https://careers.mra.mw/',
        NULL,
        'Malawi',
        false,
        false,
        720,
        92,
        true,
        true,
        'Official MRA recruitment portal. Disabled until dynamic portal extraction is reviewed.',
        '{"maxLinks": 30, "linkIncludeKeywords": ["job", "jobs", "requisition", "career", "apply"]}'::jsonb,
        ARRAY['job', 'career', 'requisition'],
        ARRAY['privacy', 'terms', 'login', 'signin'],
        ARRAY['mra', 'malawi revenue authority', 'job', 'apply']
    ),
    (
        'Reserve Bank of Malawi Vacancies',
        'rbm-vacancies',
        'CAREER_PAGE',
        'https://www.rbm.mw/mediacenter/vacancies/',
        NULL,
        'Malawi',
        true,
        false,
        720,
        92,
        true,
        true,
        'Official Reserve Bank of Malawi vacancies page.',
        '{"maxLinks": 25, "linkIncludeKeywords": ["vacancy", "vacancies", "career", "advert", "pdf", "job"]}'::jsonb,
        ARRAY['vacanc', 'career', 'advert', '.pdf'],
        ARRAY['privacy', 'terms', 'facebook', 'instagram', 'linkedin'],
        ARRAY['vacancy', 'reserve bank', 'rbm', 'apply']
    ),
    (
        'ESCOM Vacancies',
        'escom-vacancies',
        'CAREER_PAGE',
        'https://www.escom.mw/vacancies/',
        NULL,
        'Malawi',
        true,
        false,
        720,
        92,
        true,
        true,
        'Official ESCOM vacancies page.',
        '{"maxLinks": 25, "linkIncludeKeywords": ["vacancy", "vacancies", "career", "job", "apply", "pdf"]}'::jsonb,
        ARRAY['vacanc', 'career', 'job', '.pdf'],
        ARRAY['privacy', 'terms', 'facebook', 'instagram', 'linkedin'],
        ARRAY['vacancy', 'escom', 'apply']
    ),
    (
        'MACRA Vacancies',
        'macra-vacancies',
        'CAREER_PAGE',
        'https://macra.mw/vacancies/',
        NULL,
        'Malawi',
        true,
        false,
        720,
        92,
        true,
        true,
        'Official MACRA vacancies page.',
        '{"maxLinks": 25, "linkIncludeKeywords": ["vacancy", "vacancies", "career", "job", "apply", "pdf"]}'::jsonb,
        ARRAY['vacanc', 'career', 'job', '.pdf'],
        ARRAY['privacy', 'terms', 'facebook', 'instagram', 'linkedin'],
        ARRAY['vacancy', 'macra', 'apply']
    ),
    (
        'Malawi Government Advertisements',
        'malawi-government-advertisements',
        'CAREER_PAGE',
        'https://www.malawi.gov.mw/index.php/resources/news-and-media/advertisements',
        NULL,
        'Malawi',
        true,
        false,
        720,
        86,
        true,
        true,
        'Official Malawi Government advertisements page. Source filters prioritize vacancy links and exclude scholarships/tenders where possible.',
        '{"maxLinks": 30, "linkIncludeKeywords": ["vacancy", "vacancies", "recruitment", "job", "career", "pdf"], "linkExcludeKeywords": ["scholarship", "tender", "press release"]}'::jsonb,
        ARRAY['vacanc', 'recruit', 'job', '.pdf'],
        ARRAY['scholarship', 'tender', 'press-release', 'privacy', 'terms'],
        ARRAY['vacancy', 'recruitment', 'government', 'apply']
    ),
    (
        'Lilongwe City Council Careers',
        'lilongwe-city-council-careers',
        'CAREER_PAGE',
        'https://lcc.mw/careers/',
        NULL,
        'Lilongwe',
        true,
        false,
        720,
        86,
        true,
        true,
        'Official Lilongwe City Council careers page.',
        '{"maxLinks": 30, "linkIncludeKeywords": ["career", "vacancy", "vacancies", "job", "post", "apply"]}'::jsonb,
        ARRAY['career', 'vacanc', 'job'],
        ARRAY['privacy', 'terms', 'facebook', 'instagram', 'linkedin'],
        ARRAY['vacancy', 'career', 'lilongwe', 'apply']
    )
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    connector_type = EXCLUDED.connector_type,
    base_url = EXCLUDED.base_url,
    feed_url = EXCLUDED.feed_url,
    default_location = EXCLUDED.default_location,
    auto_publish = EXCLUDED.auto_publish,
    crawl_frequency_minutes = EXCLUDED.crawl_frequency_minutes,
    reputation_score = EXCLUDED.reputation_score,
    terms_reviewed = EXCLUDED.terms_reviewed,
    attribution_required = EXCLUDED.attribution_required,
    compliance_notes = EXCLUDED.compliance_notes,
    selector_config = EXCLUDED.selector_config,
    path_whitelist = EXCLUDED.path_whitelist,
    path_blacklist = EXCLUDED.path_blacklist,
    discovery_keywords = EXCLUDED.discovery_keywords,
    updated_at = NOW();
